### ISSUE TITLE
Tweaks for Slideshow

### ISSUE THREAD

**Issue by simoncorry** [visiblemiles/frontend#31]
Slideshow should show title of first slide as image credit:

<img width="773" alt="Screen Shot 2019-07-03 at 11 17 32 AM" src="https://user-images.githubusercontent.com/691178/60607735-dcaf4600-9d8b-11e9-8b1f-0d5fc59e4e6f.png">

In the edge case that there is only 1 slide hide the white Navigator bar:

<img width="1382" alt="Screen Shot 2019-07-02 at 4 00 22 PM" src="https://user-images.githubusercontent.com/691178/60607819-0cf6e480-9d8c-11e9-8adc-22e9f117e5f7.png">

Slides should start at the displayed value of 1 not the index value of 0. In the example below 0/8 would become 1/8:

<img width="586" alt="Screen Shot 2019-07-03 at 12 11 46 PM" src="https://user-images.githubusercontent.com/691178/60607915-3879cf00-9d8c-11e9-96b1-a1bf581360cd.png">

**Comment by EricWVGG** [comment]
that edge case is due to an outdated backend seed
